// File generated by docs_parser script. DO NOT EDIT!

package parse

var BuiltinTypes = map[string]*JavaType{
    "String": &JavaType{
        Name: "String",
        PackageName: "java.lang",
        Visibility: VisibilityPublic,
        Fields: []*JavaField{
            &JavaField{
                Name: "CASE_INSENSITIVE_ORDER",
          },
    },
}
